### ISSUE TITLE
LIExplorer_Public not working on Device

### ISSUE THREAD

**Issue by kittu4ios** [vijayviswas/TestLK#1]
Hi When i am using LIExplorer_Public in registerKey its not showing anything. Can you please let me know whether i need to change anything.

**Comment by vijayviswas** [comment]
Can you please try the latest version(2.0.0) of LIExporer.framework  as I made it as public on last week?
https://github.com/vijayviswas/LIExplorer/releases/tag/2.0.0
Please update me.
